apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  labels:
    app: notes-app
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  type: ClusterIP
